-- CREATE TABLE usuario (
--                              id BIGINT AUTO_INCREMENT PRIMARY KEY,
--                              nome VARCHAR(255) NOT NULL,
--                              email VARCHAR(255) NOT NULL,
--                              senha VARCHAR(255) NOT NULL,
--                              role VARCHAR(50) NOT NULL,
--                              ativo BOOLEAN NOT NULL,
--                              data_criacao DATETIME NOT NULL,
--                              data_atualizacao DATETIME NOT NULL
-- );
--
